# Generated by Django 6.0.6 on 2026-06-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistoryDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=255)),
                ('session_title', models.CharField(default='New Chat', max_length=255)),
                ('messages', models.TextField(default='[]')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chat_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('hashed_password', models.CharField(max_length=255)),
                ('avatar', models.CharField(default='🧑', max_length=10)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user', models.CharField(max_length=150)),
                ('action', models.CharField(choices=[('delete_user', 'Deleted User'), ('delete_session', 'Deleted Session'), ('ban_user', 'Banned User'), ('export', 'Exported Data'), ('other', 'Other')], max_length=50)),
                ('target', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
