# Generated by Django 6.0.6 on 2026-06-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'failed_logins',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('delete_user', 'Deleted User'), ('delete_session', 'Deleted Session'), ('ban_user', 'Banned User'), ('unban_user', 'Unbanned User'), ('bookmark', 'Bookmarked Session'), ('export', 'Exported Data'), ('other', 'Other')], max_length=50),
        ),
    ]
